/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;


import javax.swing.JOptionPane;


/**
 *
 * @author bushra
 */
public class AddnewStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddnewStudent
     */
    Teacher teacher;
   
    public AddnewStudent( Teacher teacher)
    {
        initComponents();
        this.teacher=teacher;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }
    public AddnewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_name = new javax.swing.JTextField();
        tf_courseID = new javax.swing.JTextField();
        tf_studentsID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel1.setText("Student Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(109, 221, 150, 52);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel2.setText("Course_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(109, 105, 120, 52);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel3.setText("Student_ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(109, 163, 120, 52);
        getContentPane().add(TF_name);
        TF_name.setBounds(298, 221, 320, 50);
        getContentPane().add(tf_courseID);
        tf_courseID.setBounds(298, 105, 320, 52);

        tf_studentsID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_studentsIDActionPerformed(evt);
            }
        });
        getContentPane().add(tf_studentsID);
        tf_studentsID.setBounds(298, 163, 320, 50);

        btnAdd.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(230, 320, 210, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel4.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel4.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -110, 780, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_studentsIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_studentsIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_studentsIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Student student = new Student();
        student.COURSE_ID = tf_courseID.getText();
        student.Student_ID = tf_studentsID.getText();
        student.name = TF_name.getText();
       
       Teacher teacher1 = new Teacher( teacher.userName,teacher.password,teacher.courseCode );
       
       
       if("Math01".equals(teacher.courseCode))
        {
            
             teacher1.AddMathsStudent(student);
             JOptionPane.showMessageDialog(rootPane, "User added successfully.");
           
        }
        
        if("PST03".equals(teacher.courseCode))
        {
            teacher1.AddPSTStudent(student);
             JOptionPane.showMessageDialog(rootPane, "User added successfully.");
        }
        
        if("English02".equals(teacher.courseCode))
        {
            teacher1.AddENGStudent(student);
             JOptionPane.showMessageDialog(rootPane, "User added successfully.");
        }
       
      
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddnewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddnewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddnewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddnewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddnewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_name;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf_courseID;
    private javax.swing.JTextField tf_studentsID;
    // End of variables declaration//GEN-END:variables
}
