/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;

import javax.swing.JOptionPane;

/**
 *
 * @author bushra
 */
public class ViewTeacher_CreateExam extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_CreateExam
     */
    Teacher teacher;
    public ViewTeacher_CreateExam(Teacher teacher) 
    {
        initComponents();
        this.teacher = teacher;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TF_Question = new javax.swing.JTextArea();
        btnaddquestion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_b = new javax.swing.JTextField();
        TF_r = new javax.swing.JTextField();
        TF_a = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tf_QID = new javax.swing.JTextField();
        TF_c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter your question");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 110, 260, 90);

        TF_Question.setColumns(20);
        TF_Question.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        TF_Question.setRows(5);
        jScrollPane1.setViewportView(TF_Question);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(273, 98, 454, 114);

        btnaddquestion.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnaddquestion.setText("Add Question");
        btnaddquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddquestionActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddquestion);
        btnaddquestion.setBounds(290, 430, 162, 58);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Option A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 250, 90, 20);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Option B");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 290, 90, 20);

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Option C");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 330, 70, 30);
        getContentPane().add(TF_b);
        TF_b.setBounds(348, 285, 255, 37);
        getContentPane().add(TF_r);
        TF_r.setBounds(350, 380, 255, 37);
        getContentPane().add(TF_a);
        TF_a.setBounds(348, 241, 255, 37);

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter QID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(481, 37, 124, 34);

        Tf_QID.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        getContentPane().add(Tf_QID);
        Tf_QID.setBounds(611, 37, 100, 34);
        getContentPane().add(TF_c);
        TF_c.setBounds(350, 330, 255, 37);

        jLabel6.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Result");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 370, 90, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel7.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel7.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -110, 800, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddquestionActionPerformed
       
        //Teacher teacher = new Teacher();
        Exam exam= new Exam();
        exam.QID = Tf_QID.getText();
        exam.question = TF_Question.getText();
        exam.optionA = TF_a.getText();
        exam.optionB = TF_b.getText();
        exam.optionC = TF_c.getText();
        exam.Result = TF_r.getText();
        exam.teacher = this.teacher;
        
      //Exam exam2 = new Exam( exam.QID, exam.question,exam.optionA , exam.optionB, exam.optionC,exam.Result);
       exam.InsertQuestions();
       JOptionPane.showMessageDialog(rootPane, "Question added successfully.");
    }//GEN-LAST:event_btnaddquestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CreateExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TF_Question;
    private javax.swing.JTextField TF_a;
    private javax.swing.JTextField TF_b;
    private javax.swing.JTextField TF_c;
    private javax.swing.JTextField TF_r;
    private javax.swing.JTextField Tf_QID;
    private javax.swing.JButton btnaddquestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
