/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;

import javax.swing.JOptionPane;

/**
 *
 * @author bushra
 */
public class ViewTeacherSignUP extends javax.swing.JFrame {

    /**
     * Creates new form TeacherSignUP
     */
    public ViewTeacherSignUP() {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_cc = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Your Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(177, 84, 169, 54);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Course Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(177, 229, 204, 49);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(177, 162, 204, 52);
        getContentPane().add(tf_cc);
        tf_cc.setBounds(404, 231, 266, 49);

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(404, 89, 266, 49);
        getContentPane().add(tf_pass);
        tf_pass.setBounds(404, 166, 266, 49);

        btnSignUp.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignUp.setContentAreaFilled(false);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(287, 334, 199, 64);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel4.setBounds(new java.awt.Rectangle(0, -110, 770, 710));
        jLabel4.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel4.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel4.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-5, -4, 820, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
       Teacher teacher = new Teacher();
       teacher.userName = tf_name.getText();
       teacher.password = tf_pass.getText();
       teacher.courseCode = tf_cc.getText();
       
       Teacher teacher_toadddata = new Teacher( teacher.userName ,teacher.password , teacher.courseCode);
       teacher_toadddata.InsertData(teacher);
       JOptionPane.showMessageDialog(rootPane, "User added successfully.");
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherSignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherSignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherSignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherSignUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeacherSignUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField tf_cc;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_pass;
    // End of variables declaration//GEN-END:variables
}
