/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;

/**
 *
 * @author bushra
 */
public class ViewStudent_MainPage extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudent_MainPage
     */
    
    Student student;
    
    public ViewStudent_MainPage()
    {
    }
    public ViewStudent_MainPage(Student student) 
    {
        initComponents();
        this.student=student;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        jLabel1_welcome.setText("Welcome, "+student.name);
        
        jTextArea1_info.setText("Name: "+student.name);
        jTextArea1_info.setText(jTextArea1_info.getText()+"\n");
        jTextArea1_info.setText(jTextArea1_info.getText()+"Course Code: "+student.COURSE_ID);
        jTextArea1_info.setText(jTextArea1_info.getText()+"\n");
        jTextArea1_info.setText(jTextArea1_info.getText()+"Student ID: "+student.Student_ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1_welcome = new javax.swing.JLabel();
        btnpaper = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_info = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton3.setText("Check Results");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1_welcome.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1_welcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_welcome.setText("Welcome,");
        getContentPane().add(jLabel1_welcome);
        jLabel1_welcome.setBounds(57, 120, 290, 90);

        btnpaper.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        btnpaper.setText("Start Paper");
        btnpaper.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaperActionPerformed(evt);
            }
        });
        getContentPane().add(btnpaper);
        btnpaper.setBounds(100, 280, 567, 56);

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 204));

        jTextArea1_info.setEditable(false);
        jTextArea1_info.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.background"));
        jTextArea1_info.setColumns(20);
        jTextArea1_info.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(jTextArea1_info);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 80, 370, 110);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 40, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -110, 760, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaperActionPerformed
        // TODO add your handling code here:
        new ViewStudent_Exam(student).setVisible(true);
        this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnpaperActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudent_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpaper;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_welcome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_info;
    // End of variables declaration//GEN-END:variables
}
