
package examb;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bushra
 */
public class ViewTeacher_CheckResult extends javax.swing.JFrame {

    /**
     * Creates new form ViewTeacher_CheckResult
     */
    Teacher teacher;
    ResultSet rs; 
    public ViewTeacher_CheckResult() {
        initComponents();
    }
    public ViewTeacher_CheckResult(Teacher teacher) 
    {
        initComponents();
        this.teacher=teacher;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        Student student= new Student();
        
        if("PST03".equals(teacher.courseCode))
        {
            try
                {

                rs = student.ShowAllPSTResults();
                    
                while(jTable1_showresult.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_showresult.getModel()).removeRow(0);

                }


                
                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1_showresult.getModel()).insertRow(rs.getRow()-1,row);
                }

            }
            catch (Exception e)
        {
                
        }  
        }
        if("Math01".equals(teacher.courseCode))
        {
            
            
            try
                {

                rs = student.ShowAllMathsResults();
                    
                while(jTable1_showresult.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_showresult.getModel()).removeRow(0);

                }

                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel)jTable1_showresult.getModel()).insertRow(rs.getRow()-1,row);
                }

            }
        catch (Exception e)
        {
                
        }  
        }
        if("English02".equals(teacher.courseCode))
        {
            
            
            try
                {

                rs = student.ShowAllENGResults();
                    
                while(jTable1_showresult.getRowCount() > 0) 
                {
                    ((DefaultTableModel) jTable1_showresult.getModel()).removeRow(0);

                }

                int columns = rs.getMetaData().getColumnCount();


                while(rs.next())
                {  

                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++)
                    {  
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel)jTable1_showresult.getModel()).insertRow(rs.getRow()-1,row);
                }

            }
        catch (Exception e)
        {
                
        }  
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_showresult = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1_search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_file = new javax.swing.JMenu();
        jMenuItem_refresh = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1_showresult.setBackground(new java.awt.Color(0, 0, 102));
        jTable1_showresult.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jTable1_showresult.setForeground(new java.awt.Color(255, 255, 255));
        jTable1_showresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student_ID", "Student Name", "Total Marks", "Obtained Marks"
            }
        ));
        jScrollPane1.setViewportView(jTable1_showresult);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 790, 330);

        jTextField1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(34, 9, 579, 50);

        jButton1_search.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_search.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jButton1_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_search.setText("Search");
        jButton1_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_search.setContentAreaFilled(false);
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search);
        jButton1_search.setBounds(631, 9, 110, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/backarrow copy.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 410, 140, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel1.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel1.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -110, 790, 710);

        jMenuBar1.setBackground(new java.awt.Color(121, 228, 255));

        jMenu1_file.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1_file.setText("File");

        jMenuItem_refresh.setText("Refresh");
        jMenuItem_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_refreshActionPerformed(evt);
            }
        });
        jMenu1_file.add(jMenuItem_refresh);

        jMenuBar1.add(jMenu1_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed

        Student student= new Student();
        if("Math01".equals(teacher.courseCode))
        {

            rs = student.SearchMathStudentsResult(jTextField1.getText());
        }

        if("English02".equals(teacher.courseCode))
        {

            rs = student.SearchENGStudentsResult(jTextField1.getText());
        }
        if("PST03".equals(teacher.courseCode))
        {

            rs = student.SearchPSTStudentsResult(jTextField1.getText());
        }
        try
        {

            while(jTable1_showresult.getRowCount() > 0)
            {
                ((DefaultTableModel) jTable1_showresult.getModel()).removeRow(0);
            }
            int columns = rs.getMetaData().getColumnCount();
            while(rs.next())
            {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {
                    row[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) jTable1_showresult.getModel()).insertRow(rs.getRow()-1,row);
            }

        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton1_searchActionPerformed

    private void jMenuItem_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_refreshActionPerformed
        jTextField1.setText("");
        this.jButton1_searchActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_refreshActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewTeacherMainPage(teacher).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CheckResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CheckResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CheckResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_CheckResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeacher_CheckResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1_file;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_showresult;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
