/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;
import java.sql.ResultSet;

import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JOptionPane;


/**
 *
 * @author bushra
 */
public class ViewStudent_Exam extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudent_Exam
     */
    public ViewStudent_Exam() {
        initComponents();
    }
    Student student;
    ResultSet rs;
    String result=null;
    int count=0;
    Timer timer;
   
    
    public ViewStudent_Exam(Student student)
    {
        initComponents();
        this.student=student;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        
        
        
        lblScore.setText("Score: 0 / 50");
       
        rs=null;
        
        if(student.COURSE_ID.equals("PST03"))
        {
        rs= student.GetNextQuestion("QuestionBankPST");
        }
        if(student.COURSE_ID.equals("Math01"))
        {
        rs= student.GetNextQuestion("QuestionBankMaths");
        }
        if(student.COURSE_ID.equals("English02"))
        {
        rs= student.GetNextQuestion("QuestionBankEnglish");
        }
        
        int record = 0;
        
        try
        {
            while(rs.next())
            {
               record++;//after record is found we extract following

                 //filling form
                tfQuestionText.setText(rs.getString("Question"));
                rbOptionA.setText(rs.getString("A"));
                rbOptionB.setText(rs.getString("B"));               
                rbOptionC.setText(rs.getString("C"));
                
                result=rs.getString("Result");
            }
        }
        
        catch (Exception e)
        {
        
        }
        
        
        //for setting up 15mins timer (900 seconds)
        timer = new Timer();
        
        
        TimerTask task;
        task = new TimerTask()
        {
            int i=20; //because in 15mins there are 900secs
            public void run()
            {
                if(i>=0)
                {
                    String time = String.format("%02d:%02d", i/60, i%60); //60 because each minute has 60 seconds
                    lblTimer.setText("Time Left: " + time);
                    i--;
                    
                }
                else
                {
                    timer.cancel();
                    
                    //calculate final result, show messagebox prompt and then show next form of result
                    JOptionPane.showMessageDialog(rootPane, "Time Limit Exceeded,Exam Over.");
                    new ViewStudent_examlastpage(student, count).setVisible(true);
                    ViewStudent_Exam.this.setVisible(false);
        
                }
                
                
            }
            
            
        };
                
        timer.scheduleAtFixedRate(task, 0, 1000); //0 is delay before each execution of task and 
                                        //1000 is miliseconds interval between each execution of task
        

 
 

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnNextQuestion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfQuestionText = new javax.swing.JTextArea();
        rbOptionA = new javax.swing.JRadioButton();
        rbOptionB = new javax.swing.JRadioButton();
        rbOptionC = new javax.swing.JRadioButton();
        lblScore = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        btnNextQuestion.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnNextQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/nextarrow.png"))); // NOI18N
        btnNextQuestion.setBorder(null);
        btnNextQuestion.setContentAreaFilled(false);
        btnNextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(btnNextQuestion);
        btnNextQuestion.setBounds(500, 360, 260, 100);

        tfQuestionText.setEditable(false);
        tfQuestionText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        tfQuestionText.setColumns(20);
        tfQuestionText.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        tfQuestionText.setRows(5);
        jScrollPane1.setViewportView(tfQuestionText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 700, 140);

        buttonGroup1.add(rbOptionA);
        rbOptionA.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        rbOptionA.setForeground(new java.awt.Color(255, 255, 255));
        rbOptionA.setText("jRadioButton1");
        getContentPane().add(rbOptionA);
        rbOptionA.setBounds(72, 243, 280, 50);

        buttonGroup1.add(rbOptionB);
        rbOptionB.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        rbOptionB.setForeground(new java.awt.Color(255, 255, 255));
        rbOptionB.setText("jRadioButton2");
        getContentPane().add(rbOptionB);
        rbOptionB.setBounds(476, 243, 270, 50);

        buttonGroup1.add(rbOptionC);
        rbOptionC.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        rbOptionC.setForeground(new java.awt.Color(255, 255, 255));
        rbOptionC.setText("jRadioButton3");
        getContentPane().add(rbOptionC);
        rbOptionC.setBounds(269, 306, 400, 50);

        lblScore.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("//count label//");
        getContentPane().add(lblScore);
        lblScore.setBounds(490, 160, 210, 70);

        lblTimer.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 51, 51));
        lblTimer.setText("timer counter here");
        getContentPane().add(lblTimer);
        lblTimer.setBounds(20, 380, 239, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -110, 770, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextQuestionActionPerformed
        // TODO add your handling code here:
        
        
    
        
        
        if(rbOptionA.isSelected())
        {
            if(rbOptionA.getText().equals(result))
            {
                count+=5;
            }
        }
        else if(rbOptionB.isSelected())
        {
            if(rbOptionB.getText().equals(result))
            {
                count+=5;
            }
            
        }
        else if(rbOptionC.isSelected())
        {
            if(rbOptionC.getText().equals(result))
            {
                count+=5;
            }
            
        }
        
        
        
        
        
        ResultSet rs=null;
        
        if(student.COURSE_ID.equals("PST03"))
        {
        rs= student.GetNextQuestion("QuestionBankPST");
        }
        if(student.COURSE_ID.equals("Math01"))
        {
        rs= student.GetNextQuestion("QuestionBankMaths");
        }
        if(student.COURSE_ID.equals("English02"))
        {
        rs= student.GetNextQuestion("QuestionBankEnglish");
        }
        
        int record = 0;
        
        try
        {
            while(rs.next())
            {
               record++;//after record is found we extract following

                 //filling form
                tfQuestionText.setText(rs.getString("Question"));
                rbOptionA.setText(rs.getString("A"));
                rbOptionB.setText(rs.getString("B"));               
                rbOptionC.setText(rs.getString("C"));
                result=rs.getString("Result");
                
                
                
            }
        }
        
        
        catch (Exception e)
        {
        
        }
        
        lblScore.setText("Score: "+String.valueOf(count)+ " / 50");
        
            //clearing radio button selection
        buttonGroup1.clearSelection();
        
      if (student.questionNumber==11)
        {
            timer.cancel();
            new ViewStudent_examlastpage(student, count).setVisible(true);
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_btnNextQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent_Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudent_Exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextQuestion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JRadioButton rbOptionA;
    private javax.swing.JRadioButton rbOptionB;
    private javax.swing.JRadioButton rbOptionC;
    private javax.swing.JTextArea tfQuestionText;
    // End of variables declaration//GEN-END:variables
}
