/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;

/**
 *
 * @author bushra
 */
public class ViewTeacher_EnrollStudent extends javax.swing.JFrame {

    /**
     * Creates new form ViewTeacher_EnrollStudent
     */
    Teacher teacher;
    public ViewTeacher_EnrollStudent() 
    {
    }
    public ViewTeacher_EnrollStudent(Teacher t) 
    {
        initComponents();
        this.teacher = t;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpst = new javax.swing.JButton();
        btnenglish = new javax.swing.JButton();
        btnmath = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose the course for student enrollment.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 64, 414, 57);

        btnpst.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnpst.setText("PST");
        btnpst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpstActionPerformed(evt);
            }
        });
        getContentPane().add(btnpst);
        btnpst.setBounds(231, 234, 209, 75);

        btnenglish.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnenglish.setText("English");
        btnenglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnenglish);
        btnenglish.setBounds(231, 327, 209, 75);

        btnmath.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnmath.setText("Maths");
        btnmath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmathActionPerformed(evt);
            }
        });
        getContentPane().add(btnmath);
        btnmath.setBounds(231, 147, 209, 75);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/backarrow copy.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 360, 130, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(5196, 3200));
        jLabel2.setMinimumSize(new java.awt.Dimension(5196, 3200));
        jLabel2.setPreferredSize(new java.awt.Dimension(5196, 3200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -110, 770, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmathActionPerformed
                   
                    new ViewTeacher_EnrollStudentTable(teacher).setVisible(true);
                    this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnmathActionPerformed

    private void btnpstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpstActionPerformed
                    
                    new ViewTeacher_EnrollStudentTable(teacher).setVisible(true);
                    this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnpstActionPerformed

    private void btnenglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenglishActionPerformed
        // TODO add your handling code here:
                    new ViewTeacher_EnrollStudentTable(teacher).setVisible(true);
                    this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnenglishActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewTeacherMainPage(teacher).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_EnrollStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_EnrollStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_EnrollStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher_EnrollStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeacher_EnrollStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenglish;
    private javax.swing.JButton btnmath;
    private javax.swing.JButton btnpst;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
