/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examb;

/**
 *
 * @author bushra
 */
public class ViewTeacherMainPage extends javax.swing.JFrame {

    /**
     * Creates new form TeacherMainPage
     */
    
    Teacher teacher;
    
     public ViewTeacherMainPage() {
        initComponents();
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        

        
    }
    
    public ViewTeacherMainPage( Teacher teacher) {
        initComponents();
        
        this.teacher = teacher;
        this.setLocationRelativeTo(null); // for centering form on screen
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //does not close app on exit of window
        label_welcome.setText("Welcome, "+teacher.userName);
        
        label_profile.setText("Name: "+teacher.userName);
        label_profile.setText(label_profile.getText()+"\n");
        label_profile.setText(label_profile.getText()+"Course Code: "+teacher.courseCode);
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_welcome = new javax.swing.JLabel();
        btnenrollstudent = new javax.swing.JButton();
        btnAddnewQuestions = new javax.swing.JButton();
        btnresult = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        label_profile = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 500, 770, 522));
        setPreferredSize(new java.awt.Dimension(770, 522));
        setResizable(false);
        getContentPane().setLayout(null);

        label_welcome.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        label_welcome.setForeground(new java.awt.Color(255, 255, 255));
        label_welcome.setText("Welcome,");
        getContentPane().add(label_welcome);
        label_welcome.setBounds(36, 80, 300, 100);

        btnenrollstudent.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnenrollstudent.setForeground(new java.awt.Color(255, 255, 255));
        btnenrollstudent.setText("Enroll Students");
        btnenrollstudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnenrollstudent.setContentAreaFilled(false);
        btnenrollstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenrollstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnenrollstudent);
        btnenrollstudent.setBounds(210, 212, 251, 76);

        btnAddnewQuestions.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnAddnewQuestions.setForeground(new java.awt.Color(255, 255, 255));
        btnAddnewQuestions.setText("Add new Questions");
        btnAddnewQuestions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddnewQuestions.setContentAreaFilled(false);
        btnAddnewQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnewQuestionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddnewQuestions);
        btnAddnewQuestions.setBounds(210, 294, 251, 67);

        btnresult.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnresult.setForeground(new java.awt.Color(255, 255, 255));
        btnresult.setText("Result");
        btnresult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnresult.setContentAreaFilled(false);
        btnresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresultActionPerformed(evt);
            }
        });
        getContentPane().add(btnresult);
        btnresult.setBounds(210, 367, 251, 73);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Teacher Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 20, 251, 40);

        label_profile.setEditable(false);
        label_profile.setColumns(20);
        label_profile.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        label_profile.setRows(5);
        jScrollPane1.setViewportView(label_profile);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(452, 58, 290, 142);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/backarrow copy.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 380, 110, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examb/examb_images/bg.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setMinimumSize(new java.awt.Dimension(5169, 3200));
        jLabel2.setPreferredSize(new java.awt.Dimension(5169, 3200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -110, 770, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresultActionPerformed
        // TODO add your handling code here:
        new ViewTeacher_CheckResult(teacher).setVisible(true);
        this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnresultActionPerformed

    private void btnAddnewQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnewQuestionsActionPerformed
        
                new ViewTeacher_CreateExam(teacher).setVisible(true);
                this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnAddnewQuestionsActionPerformed

    private void btnenrollstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenrollstudentActionPerformed
        // TODO add your handling code here:
                new ViewTeacher_EnrollStudent(teacher).setVisible(true);
                this.setVisible(false); //to close current window
    }//GEN-LAST:event_btnenrollstudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewTeacherLoginPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacherMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeacherMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddnewQuestions;
    private javax.swing.JButton btnenrollstudent;
    private javax.swing.JButton btnresult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea label_profile;
    private javax.swing.JLabel label_welcome;
    // End of variables declaration//GEN-END:variables
}
